### ISSUE TITLE
Add translation for [Vietnamese]

### ISSUE THREAD

**Issue by vuduclyunitn** [satwikkansal/wtfpython#195]
Expected time to finish: [4] weeks. I'll start working on it from [04/13/2020].

**Comment by satwikkansal** [comment]
Hi @vuduclyunitn 

Thanks for considering this, feel free to ask any questions / doubts you face during the tranlation :)

**Comment by vuduclyunitn** [comment]
Hi @satwikkansal, sorry for completing the translation late. I have completed the translation for the Vietnamese language at https://github.com/vuduclyunitn/wtfpython/blob/master/README.md. Please let me know how to proceed to integrate the translation to the main page of wtfpython. Thanks.

**Comment by satwikkansal** [comment]
Hi @vuduclyunitn 

Wow, thanks, that looks neat. 

I'll take care of linking your repo to the English one and adding credits :) Meanwhile, I have a couple of minor requests,

- Could you please link to the English version in your repo (just like how the chinese version is linked at the top)
- If it's okay, can you change the name of your fork to `wtfptyhon-vi` so that it's easier for others to look it up.

Finally, to add an interactive version, you can simply do this,

```sh
$ cd irrelevant
$ python notebook_generator.py
```

This shall output a jupyter notebook in Vietnamese if you run it in your repo. You can commit the updated notebook to your repo, create a google colab using your repo link, and then update the interactive link as well. It should look something like [this](https://colab.research.google.com/drive/1_NtCHdK1zr-21rfE7z7Lt36XTN5R6REh?usp=sharing).

**Comment by satwikkansal** [comment]
Thanks @vuduclyunitn 

I've published your changes in the above commit. Let me know if you see any glitches.

Once again, thank you so much, I hope you enjoyed translating the project :)
