### ISSUE TITLE
Explain meaning of asterisk in heading titles

### ISSUE THREAD

**Issue by arthur-tacca** [satwikkansal/wtfpython#219]
A lot of the headings end in a asterisk e.g. "First things first! *" does but "Strings can be tricky sometimes" does not. This suggests a footnote but after quite a bit of searching I can't find one. Perhaps it means something else like "new" or "reader contributed". Please explain on the page otherwise there's not much point it being there and it's a bit frustrating.

**Comment by satwikkansal** [comment]
Those were included for the returning readers whenever a major update was released. A quick way for them to just go over what's updated (and new) instead of going over the whole project again. This is mentioned in the [released notes](https://github.com/satwikkansal/wtfpython/releases/).

> Please explain on the page otherwise there's not much point it being there and it's a bit frustrating.

I see, I'll update it in the main page.
