### ISSUE TITLE
output of "Strings can be tricky sometimes" is incorrect

### ISSUE THREAD

**Issue by simpleapples** [satwikkansal/wtfpython#62]
on python3.6.3 and python2.7.10
```
a = "wtf!"
b = "wtf!"
print(a is b)  # True
```

**Comment by satwikkansal** [comment]
Hey @simpleapples 

Thanks for creating the issue. Could you please check it again? Because I've tried in my interpreter at it outputs `False` (as expected)

![image](https://user-images.githubusercontent.com/10217535/35505079-f01c5d38-050a-11e8-83ef-b15110f653d6.png)
![image](https://user-images.githubusercontent.com/10217535/35505112-12e17498-050b-11e8-8fae-5edc5616e7b7.png)

**Comment by satwikkansal** [comment]
The versions are slightly different from those you mentioned, but I don't think that should make any difference.

**Comment by simpleapples** [comment]
It's correct when you run the code in IDLE, but it‘s incorrect when you run the code from a file.

**Comment by simpleapples** [comment]
![screen shot 2018-01-31 at 7 43 28 pm](https://user-images.githubusercontent.com/1655036/35621388-1faaea96-06bf-11e8-9302-9c8731db6198.png)
![screen shot 2018-01-31 at 7 43 45 pm](https://user-images.githubusercontent.com/1655036/35621389-1fd8ad82-06bf-11e8-807f-c23d5ace2117.png)

**Comment by shashank1094** [comment]
In the article https://github.com/satwikkansal/wtfpython#-is-is-not-what-it-is The last line gives the answer to your question/doubt 

> It's a compiler optimization and specifically applies to the interactive environment. When you enter two lines in a live interpreter, they're compiled separately, therefore optimized separately. If you were to try this example in a .py file, you would not see the same behavior, because the file is compiled all at once.

**Comment by simpleapples** [comment]
@satwikkansal @shashank1094 Thx, it's my mistake.
